name: Update Unity3D Repository List

on:
  #schedule:
  #  - cron: "0 * * * *" # 每小时执行一次
  workflow_dispatch: # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests PyYAML

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }} # 使用你的Personal Access Token
        run: |
          python3 .github/scripts/update_unity_repos.py

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "Shaun-Fong"
          git config --global user.email "shaunfong@qq.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "Update Unity3D repository list [$(date -u)]"
            git push https://Shaun-Fong:${{ secrets.GITHUB_TOKEN }}@github.com/Shaun-Fong/UnityInfos.git HEAD:main
          else
            echo "No changes to commit."
          fi

